udm-downloaded = Downloaded
udm-eta = ETA:
udm-download-speed = Download Speed:
udm-disk-speed = Disk Usage:
udm-elapsed = Elapsed:
udm-pause-download = Pause
udm-resume-download = Resume
udm-download-paused = Paused
udm-download-manager = Download Manager
udm-download-status = Status
udm-progress = Progress
udm-download-completed-column = Completed
udm-download-queued = Queued
udm-download-running = Running
udm-download-canceled = Canceled
udm-download-completed = Completed
udm-remove-entry = Remove entry
udm-move-entry-top = Move entry to top
udm-move-entry-up = Move entry up
udm-move-entry-down = Move entry down
udm-move-entry-bottom = Move entry to bottom
udm-remove-completed-downloads = Remove completed downloads
udm-remove-completed-downloads-confirm = Are you sure you want to remove all completed downloads from list?
udm-remove-selected-entries-confirm = Are you sure you want to remove selected entries from list?
udm-select-all-entries = Select all entries
udm-edit-selected-download-properties = Edit entry properties
udm-open-download-directory = Open download directory
udm-remove-entry-confirm = Are you sure you want to remove { $entryName } from list?
udm-display-download-task-finished-notifications = Display desktop notifications about finished tasks
udm-display-download-speed-in-bits = Display download speed in bits per second
udm-after-download-complete = Action after download is complete
udm-auto-remove-completed-downloads = Automatically remove completed downloads from list
udm-system-shutdown-countdown = System will be turned off soon...
udm-system-restart-countdown = System will be restarted soon...
udm-system-hibernate-countdown = System will be hibernated soon...
udm-system-suspend-countdown = System will be suspended soon...
udm-download-finished = { $appName } download finished. Have fun!
udm-download-failed = { $appName } download failed. Please check the log files for more information.
udm-download-manager-whats-up = The download will start soon. You can see its status by accessing { $pluginShortName } Panel via Menu => View or sidebar.
