udm-downloaded = Scaricato
udm-eta = Tempo rimanente:
udm-download-speed = Velocità di download:
udm-disk-speed = Utilizzo del disco:
udm-elapsed = Trascorso:
udm-pause-download = Pausa
udm-resume-download = Riprendi
udm-download-paused = In pausa
udm-download-manager = Gestore download
udm-download-status = Stato
udm-progress = Progresso
udm-download-completed-column = Completato
udm-download-queued = In coda
udm-download-running = In esecuzione
udm-download-canceled = Annullato
udm-download-completed = Completato
udm-remove-entry = Rimuovi voce
udm-move-entry-top = Sposta all'inizio
udm-move-entry-up = Sposta su
udm-move-entry-down = Sposta giù
udm-move-entry-bottom = Sposta in fondo
udm-remove-completed-downloads = Rimuovi i download completati
udm-remove-completed-downloads-confirm = Sei sicuro di voler rimuovere tutti i download completati dalla lista?
udm-remove-selected-entries-confirm = Sei sicuro di voler rimuovere le voci selezionate dalla lista?
udm-select-all-entries = Seleziona tutto
udm-edit-selected-download-properties = Modifica proprietà
udm-open-download-directory = Apri cartella download
udm-path-not-exists-error = Il percorso specificato non esiste.
udm-remove-entry-confirm = Sei sicuro di voler rimuovere { $entryName } dalla lista?
