udm-downloaded = Pobrano
udm-eta = Pozostało:
udm-download-speed = Prędkość pobierania:
udm-disk-speed = Użycie dysku:
udm-elapsed = Upłynęło:
udm-pause-download = Wstrzymaj
udm-resume-download = Wznów
udm-download-paused = Wstrzymane
udm-download-manager = Menedżer pobierania
udm-download-status = Stan
udm-progress = Postęp
udm-download-completed-column = Ukończono
udm-download-queued = W kolejce
udm-download-running = Uruchomione
udm-download-canceled = Anulowane
udm-download-completed = Ukończone
udm-remove-entry = Usuń wpis
udm-move-entry-top = Przenieś wpis na górę
udm-move-entry-up = Przenieś wpis w górę
udm-move-entry-down = Przenieś wpis w dół
udm-move-entry-bottom = Przenieś wpis na dół
udm-remove-completed-downloads = Usuń ukończone pobrania
udm-remove-completed-downloads-confirm = Czy na pewno chcesz usunąć wszystkie ukończone pobrania z listy?
udm-remove-selected-entries-confirm = Czy na pewno chcesz usunąć wybrane wpisy z listy?
udm-select-all-entries = Zaznacz wszystkie wpisy
udm-edit-selected-download-properties = Edytuj właściwości wpisu
udm-open-download-directory = Otwórz katalog pobierania
udm-path-not-exists-error = Podana ścieżka nie istnieje.
udm-remove-entry-confirm = Czy na pewno chcesz usunąć { $entryName } z listy?
