udm-downloaded = Загружено
udm-eta = Время до завершения:
udm-download-speed = Скорость загрузки:
udm-disk-speed = Запись на диск:
udm-elapsed = Прошло:
udm-pause-download = Пауза
udm-resume-download = Возобновить
udm-download-paused = Загрузка приостановлена
udm-download-manager = Менеджер загрузки
udm-download-status = Статус
udm-progress = Прогресс
udm-download-completed-column = Завершено
udm-download-queued = В очереди
udm-download-running = Запущено
udm-download-canceled = Отменено
udm-download-completed = Завершено
udm-remove-entry = Удалить запись
udm-move-entry-top = Переместить запись в начало
udm-move-entry-up = Переместить запись вверх
udm-move-entry-down = Переместить запись вниз
udm-move-entry-bottom = Переместить запись в конец
udm-remove-completed-downloads = Удалить завершенные загрузки
udm-remove-completed-downloads-confirm = Вы уверены, что хотите удалить все завершенные загрузки из списка?
udm-remove-selected-entries-confirm = Вы уверены, что хотите удалить выбранные записи из списка?
udm-select-all-entries = Выбрать все записи
udm-edit-selected-download-properties = Изменить свойства записи
udm-open-download-directory = Открыть каталог загрузок
udm-remove-entry-confirm = Вы уверены, что хотите удалить { $entryName } из списка?
udm-display-download-task-finished-notifications = Отображать уведомления на рабочем столе о завершенных задачах
udm-display-download-speed-in-bits = Отображать скорость загрузки в битах в секунду
udm-after-download-complete = Действие после завершения загрузки
udm-auto-remove-completed-downloads = Автоматически удалять завершенные загрузки из списка
udm-system-shutdown-countdown = Система скоро выключится...
udm-system-restart-countdown = Система скоро перезагрузится...
udm-system-hibernate-countdown = Система скоро перейдет в режим гибернации...
udm-system-suspend-countdown = Система скоро выключится...
udm-download-manager-whats-up = Загрузка начнется в ближайшее время. Вы можете увидеть его статус, обратившись к панели { $pluginShortName } через Меню => Вид или боковую панель.
