udm-downloaded = 已下载
udm-eta = 预计剩余时间：
udm-download-speed = 下载速度：
udm-disk-speed = 磁盘使用：
udm-elapsed = 已用时：
udm-pause-download = 暂停
udm-resume-download = 恢复
udm-download-paused = 已暂停
udm-download-manager = 下载管理器
udm-download-status = 状态
udm-progress = 进度
udm-download-completed-column = 已完成
udm-download-queued = 已排队
udm-download-running = 正在运行
udm-download-canceled = 已取消
udm-download-completed = 已完成
udm-remove-entry = 移除条目
udm-move-entry-top = 移到顶部
udm-move-entry-up = 向上移动
udm-move-entry-down = 向下移动
udm-move-entry-bottom = 移到底部
udm-remove-completed-downloads = 移除已完成下载
udm-remove-completed-downloads-confirm = 您确定要从列表中移除所有已完成下载吗？
udm-remove-selected-entries-confirm = 您确定要从列表中移除选定条目吗？
udm-select-all-entries = 选择所有条目
udm-edit-selected-download-properties = 编辑条目属性
udm-open-download-directory = 打开下载目录
udm-path-not-exists-error = 指定的路径不存在。
udm-remove-entry-confirm = 您确定要从列表中移除 { $entryName } 吗？
udm-display-download-task-finished-notifications = 显示已完成任务的通知
udm-display-download-speed-in-bits = 以 比特(bps) 显示下载速度
udm-after-download-complete = 下载完成后操作
udm-auto-remove-completed-downloads = 自动从列表中移除已完成下载
udm-system-shutdown-countdown = 系统即将关闭……
udm-system-restart-countdown = 系统即将重启……
udm-system-hibernate-countdown = 系统即将休眠……
udm-system-suspend-countdown = 系统即将挂起……
udm-download-manager-whats-up = 下载即将开始。您可以通过菜单 => 查看或侧边栏访问 { $pluginShortName } 面板来查看其状态。
