udm-downloaded = İndirilen
udm-eta = TTS:
udm-download-speed = İndirme Hızı:
udm-disk-speed = Disk Kullanımı:
udm-elapsed = Geçen:
udm-pause-download = Duraklat
udm-resume-download = Sürdür
udm-download-paused = Duraklatıldı
udm-download-manager = İndirme Yöneticisi
udm-download-status = Durum
udm-progress = İlerleyiş
udm-download-completed-column = Tamamlandı
udm-download-queued = Kuyrukta
udm-download-running = Çalışıyor
udm-download-canceled = Vazgeçildi
udm-download-completed = Tamamlandı
udm-remove-entry = Girdiyi kaldır
udm-move-entry-top = Girişi en üste taşı
udm-move-entry-up = Girişi üste taşı
udm-move-entry-down = Girişi alta taşı
udm-move-entry-bottom = Girişi en alta taşı
udm-remove-completed-downloads = Tamamlanan indirmeleri kaldır
udm-remove-completed-downloads-confirm = Tamamlanan tüm indirmeleri listeden kaldırmak istiyor musunuz?
udm-select-all-entries = Tüm girişleri seç
udm-edit-selected-download-properties = Girdi özelliklerini düzenle
udm-open-download-directory = İndirilenler dizinini aç
udm-display-download-task-finished-notifications = Tamamlanan görevlerle ilgili masaüstü bildirimlerini görüntüle
udm-display-download-speed-in-bits = İndirme hızını saniyedeki bit cinsinden göster
udm-after-download-complete = İndirme tamamlandıktan sonraki eylem
udm-auto-remove-completed-downloads = Tamamlanan indirmeleri otomatik olarak listeden kaldır
udm-system-shutdown-countdown = Sistem yakında kapatılacak...
udm-system-restart-countdown = Sistem yakında yeniden başlatılacak...
udm-system-hibernate-countdown = Sistem yakında hazırda bekletme moduna geçecek...
udm-system-suspend-countdown = Sistem yakında askıya alınacak...
udm-download-manager-whats-up = İndirme yakında başlayacak. Menü => Görünüm veya kenar çubuğundan { $pluginShortName } Panel üstünden durumunu görebilirsiniz.
