udm-downloaded = Transferido
udm-eta = Tempo Restante:
udm-download-speed = Veloc. de Transferência:
udm-disk-speed = Uso do Disco:
udm-elapsed = Decorrido:
udm-pause-download = Pausar
udm-resume-download = Continuar
udm-download-paused = Pausado
udm-download-manager = Gerenciador de Transferências
udm-download-status = Progresso
udm-progress = Progresso
udm-download-completed-column = Concluído
udm-download-queued = Na fila
udm-download-running = Transferindo
udm-download-canceled = Cancelado
udm-download-completed = Concluído
udm-remove-entry = Remover da lista
udm-move-entry-top = Mover item para o topo
udm-move-entry-up = Mover item para cima
udm-move-entry-down = Mover item para baixo
udm-move-entry-bottom = Mover item para o fim
udm-remove-completed-downloads = Remover transferências concluídas
udm-remove-completed-downloads-confirm = Tem certeza que deseja remover todas as transferências concluídos da lista?
udm-remove-selected-entries-confirm = Tem certeza que deseja remover os itens selecionados da lista?
udm-select-all-entries = Selecionar todos os itens
udm-edit-selected-download-properties = Editar propriedades deste item
udm-open-download-directory = Abrir diretório de transferências
udm-path-not-exists-error = O caminho especificado não existe.
udm-remove-entry-confirm = Tem certeza que deseja remover { $entryName } da lista?
udm-display-download-task-finished-notifications = Notificar na área de trabalho sobre tarefas finalizadas
udm-display-download-speed-in-bits = Exibir a velocidade de transferência em bits por segundo
udm-after-download-complete = Quando a transferência terminar
udm-auto-remove-completed-downloads = Automaticamente remover transferências concluídas da lista
udm-system-shutdown-countdown = O sistema será desligado em breve...
udm-system-restart-countdown = O sistema será reiniciado em breve...
udm-system-hibernate-countdown = O sistema hibernará em breve...
udm-system-suspend-countdown = O sistema será suspenso em breve...
