udm-downloaded = Heruntergeladen
udm-eta = Downloadzeit:
udm-download-speed = Downloadgeschwindigkeit:
udm-disk-speed = Festplattennutzung:
udm-elapsed = Vergangene Zeit:
udm-pause-download = Anhalten
udm-resume-download = Fortsetzen
udm-download-paused = Pausiert
udm-download-manager = Download-Manager
udm-progress = Fortschritt
udm-download-completed-column = Abgeschlossen
udm-download-queued = Ausstehend
udm-download-running = Aktiv
udm-download-canceled = Abgebrochen
udm-download-completed = Abgeschlossen
udm-remove-entry = Eintrag entfernen
udm-move-entry-top = Eintrag an den Anfang verschieben
udm-move-entry-up = Eintrag nach oben verschieben
udm-move-entry-down = Eintrag nach unten verschieben
udm-move-entry-bottom = Eintrag ans Ende verschieben
udm-remove-completed-downloads = Abgeschlossene Downloads entfernen
udm-remove-completed-downloads-confirm = Sind Sie sicher, dass Sie alle abgeschlossenen Downloads aus der Liste entfernen möchten?
udm-remove-selected-entries-confirm = Sind Sie sicher, dass Sie die ausgewählten Einträge aus der Liste entfernen möchten?
udm-select-all-entries = Alle Einträge auswählen
udm-edit-selected-download-properties = Eintragseigenschaften bearbeiten
udm-open-download-directory = Download-Verzeichnis öffnen
udm-path-not-exists-error = Der angegebene Pfad existiert nicht.
udm-remove-entry-confirm = Sind Sie sicher, dass Sie { $entryName } aus der Liste entfernen möchten?
