udm-downloaded = Descargado
udm-eta = Estimado:
udm-download-speed = Velocidad de descarga:
udm-disk-speed = Uso del disco:
udm-elapsed = Transcurrido:
udm-pause-download = Pausar
udm-resume-download = Reanudar
udm-download-paused = Pausado
udm-download-manager = Gestor de descargas
udm-download-status = Estado
udm-progress = Progreso
udm-download-completed-column = Completado
udm-download-queued = En cola
udm-download-running = En ejecución
udm-download-canceled = Cancelado
udm-download-completed = Completado
udm-remove-entry = Remover de la lista
udm-move-entry-top = Mover entrada a la parte superior
udm-move-entry-up = Mover entrada arriba
udm-move-entry-down = Mover entrada abajo
udm-move-entry-bottom = Mover la entrada a la parte inferior
udm-remove-completed-downloads = Eliminar descargas completadas
udm-remove-completed-downloads-confirm = ¿Estás seguro que deseas eliminar todas las descargas completadas de la lista?
udm-select-all-entries = Seleccionar todas las entradas
udm-edit-selected-download-properties = Editar propiedades de la entrada
udm-open-download-directory = Abrir directorio de descarga
udm-display-download-task-finished-notifications = Mostrar notificaciones de escritorio sobre tareas terminadas
udm-display-download-speed-in-bits = Mostrar velocidad de descarga en bits por segundo
udm-after-download-complete = Acción después de completar la descarga
udm-auto-remove-completed-downloads = Eliminar automáticamente las descargas completadas de la lista
udm-system-shutdown-countdown = El sistema se apagará pronto...
udm-system-restart-countdown = El sistema se reiniciará pronto...
udm-system-hibernate-countdown = El sistema entrará en hibernación pronto...
udm-system-suspend-countdown = El sistema se suspenderá pronto...
udm-download-manager-whats-up = La descarga comenzará pronto. Puedes ver su estado accediendo al Panel { $pluginShortName } a través del Menú => Vista o barra lateral.
