udm-downloaded = Descargado
udm-eta = Estimado:
udm-download-speed = Velocidad de descarga:
udm-disk-speed = Uso del disco:
udm-elapsed = Transcurrido:
udm-pause-download = Pausar
udm-resume-download = Reanudar
udm-download-paused = Pausado
udm-download-manager = Gestor de descargas
udm-download-status = Estado
udm-progress = Progreso
udm-download-completed-column = Completado
udm-download-queued = En cola
udm-download-running = En ejecución
udm-download-canceled = Cancelado
udm-download-completed = Completado
udm-remove-entry = Remover de la lista
udm-move-entry-top = Mover entrada a la parte superior
udm-move-entry-up = Mover entrada arriba
udm-move-entry-down = Mover entrada abajo
udm-move-entry-bottom = Mover la entrada a la parte inferior
udm-remove-completed-downloads = Eliminar descargas completadas
udm-remove-completed-downloads-confirm = ¿Estás seguro que deseas eliminar todas las descargas completadas de la lista?
udm-remove-selected-entries-confirm = ¿Estás seguro que deseas eliminar las entradas seleccionadas de la lista?
udm-select-all-entries = Seleccionar todas las entradas
udm-edit-selected-download-properties = Editar propiedades de la entrada
udm-open-download-directory = Abrir directorio de descarga
udm-path-not-exists-error = La ruta especificada no existe.
udm-remove-entry-confirm = ¿Está seguro que desea eliminar { $entryName } de la lista?
