name: Publish API as Nuget

permissions:
  contents: read

on:
  workflow_dispatch: null
  
jobs:
  package-and-publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install correct .NET
        run: |
          choco install netfx-4.6.2-devpack
      - name: Generate NuGet package
        run: |
          nuget restore src/api/UnifiedDownloadManagerApi.csproj
          nuget pack src/api/ -Build -Properties Configuration=Release -OutputDirectory NugetPackages
      - name: Publish NuGet package
        env:
          NOUGAT_TOKEN: ${{ secrets.NOUGAT_TOKEN }}
        run: |
          nuget source Add -Name "HawkeyeNougatRegistry" -Source "https://gitlab.com/api/v4/projects/85661048/packages/nuget/index.json" -Username "HawkeyeNougatHelper" -Password "$env:NOUGAT_TOKEN"
          nuget push NugetPackages\*.nupkg -Source "HawkeyeNougatRegistry"
